mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^about/$', views.About.as_view(), name='about'),
    url(r'^makepoll/$', views.MakePollView, name="makepoll"),
    url(r'^newpoll/$', views.MakePollView, name="makepoll"),
    url(r'^makechoices/(?P<poll_id>\d+)/$', views.MakeChoicesView, name="makepoll"),
    url(r'^user/(?P<user>\w+)/$', views.UserView, name="view_user"),

    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
    #Authentication/Authorization
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name='logout'),
)

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now())
    user = models.ForeignKey(User, null=True, blank=True)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.question
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <  now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class MakePoll(models.Model):
    def __unicode__(self):
        return self.question
    question = models.CharField(max_length=200)
    option0 = models.CharField(max_length=200)
    option1 = models.CharField(max_length=200)

    author = models.CharField(max_length=80)
    pub_date = models.DateTimeField('date published')


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms.models import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Layout, Submit, Button, HTML, Field
from crispy_forms.bootstrap import PrependedText, FormActions

from django.forms.formsets import formset_factory

from polls.models import Poll, Choice, MakePoll, UserProfile
from django.forms.formsets import formset_factory
from django.forms.models import BaseInlineFormSet, inlineformset_factory

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    #email = forms.EmailField(max_length=100, required=False)
    class Meta:
        model = User
        #fields = ('username', 'email', 'password')
        ## I really don't need your email and you're safer not sharing it with me
        fields = ('username', 'password')
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('post', 'post', css_class='btn-primary'))

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

'''
class MakeChoices(forms.ModelForm):
    class Meta:
        model = Choice
        exclude = ['poll', 'votes']
    #poll = Poll.objects.get(id=1)
    choice_text = forms.CharField(max_length=200)
'''

class MakePoll(forms.ModelForm):
    class Meta:
        model = Poll
        exclude = ['user']
    choice = forms.CharField(max_length=200)

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.layout = Layout(
        Field('question'),
        Field('pub_date', type='hidden'),
        Field('choice'),
        FormActions(Submit('post', 'Post!', css_class='btn-primary')),
    )

class MakeChoices(forms.Form):
    choice_text = forms.CharField(max_length=200, required=False)

polls/views.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.utils import timezone
from django.views import generic
from django.views.generic.edit import CreateView
from django.forms.formsets import formset_factory

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from polls.models import Choice, Poll
from polls.forms import MakePoll, UserForm, UserProfileForm, MakeChoices


class About(generic.TemplateView):
    template_name = 'polls/about.html'

    def get_context_data(self, **kwargs):
        context = super(About, self).get_context_data(**kwargs)
        return context

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

def UserView(request, user):
    context = RequestContext(request)
    context_dict = {'user': user}

    # why does only user__username work?? NO IDEA but it took me an hour to figure it out.
    user_polls_list = Poll.objects.filter(user__username = user).order_by('-pub_date')[:5]
    #user_polls_list = Poll.objects.values_list('id', flat=True)
    context_dict['polls'] = user_polls_list

    return render_to_response('polls/user.html', context_dict, context)

#class UserView(generic.ListView):
#    template_name = 'polls/user.html'
#    context_object_name = 'latest_user_poll_list'

#    def get_queryset(self):
#        """Return the last five published polls."""
#        return Poll.objects.filter(
#            pub_date__lte=timezone.now(),
#        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any polls that aren't published yet.
        """
        return Poll.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'
   
def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

def MakePollView(request):
    if request.method == 'POST': # If the form has been submitted...
        form = MakePoll(request.POST) # A form bound to the POST data
        choiceform = MakeChoices(request.POST)
        if (form.is_valid and choiceform.is_valid)():
            #print form.cleaned_data
            new_instance = form.save(commit=False)
            if request.user.is_authenticated():
                new_instance.user = request.user
            new_instance.save()

            choice0 = Choice.objects.create(poll = Poll.objects.get(id = new_instance.id), choice_text = form.cleaned_data.get('choice'))

            choice0.save()

            return HttpResponseRedirect('/polls/') # Redirect after POST
    else:
        form = MakePoll() # An unbound form
        choiceform = formset_factory(MakeChoices, extra=2)

    return render(request, 'polls/makepoll.html', {
        'form': form,
        'choiceform': choiceform,
        }
    )

def MakeChoicesView(request, poll_id):
    if request.method == 'POST':
        form = MakeChoices(request.POST, poll_id)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/polls/') # Redirect after POST
    else:
        form = MakeChoices() # An unbound form

    return render(request, 'polls/makepoll.html', {
        'form': form,
    })

def register(request):
    # Like before, get the request's context.
    context = RequestContext(request)

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render_to_response(
            'polls/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
            context)

def user_login(request):
    # Like before, obtain the context for the user's request.
    context = RequestContext(request)

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user is not None:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/polls/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render_to_response('polls/login.html', {}, context)

# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/polls/')

@login_required
def restricted(request):
    return render_to_response('polls/restricted.html')

polls/templates/polls/about.html
{% extends 'polls/base.html' %}
{% load static %}

{% block title %}Polls{% endblock %}

{% block body_block %}
    <h1>About: </h1>
    <p>
        Code taken mostly from my copies of the offical Django tutorial and Tango With Django.
    </p>
    <p>
        Made with: Django, django_crispy_forms, yeoman, sass (probably more but I can't remember them all right now.)
    </p>

    <p>
        Yes, I did keep the button from the yeoman installation because I think it looks nice!
    </p>
    <br>
    <p>
        To Add:
        <ul>
            <li>SSL</li>
            <li>Google Charts API</li>
            <li>view counter on about page</li>
            <li>prettier template</li>
            <li>Make sure all pages validate!</li>
            <li>Give polls an ID so that choices can be linked to them not by name.</li>
        </ul>
    </p>

{% endblock %}

polls/templates/polls/base.html
<!doctype html>

{% load staticfiles %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Kevin's Site</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <!-- build:css styles/vendor.css -->
        <!-- bower:css -->

        <!-- endbower -->
        <!-- endbuild -->
        <!-- build:css(.tmp) styles/main.css -->
        <link rel="stylesheet" href="{% static 'polls/main.css' %}">
        <!-- endbuild -->
    </head>
    <body>
        <!--[if lt IE 10]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
            <!--
            <div class="header">
                <ul class="nav nav-pills pull-right">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
                <h3 class="text-muted">Kevin's Site</h3>
            </div>
            -->

        <div class="topbar">
            {% if user.is_authenticated %}
                <p class="login"><a href="/polls/">HOME</a> | Welcome, <a href="/polls/user/{{ user.username }}/">{{ user.username }}</a> | <a href="/polls/logout/">Logout</a></p>
            {% else %}
                <p class="login"><a href="/polls/register/">Register</a> | <a href="/polls/login/#">Login</a></p>
            {% endif %}
        </div>
        <div class="jumbotron">
            
            <h1>Welcome!</h1>
            <p class="lead">Click below to make a poll.</p>
            <p><a class="btn btn-lg btn-default underlinehover" href="/polls/makepoll/">Splendid!</a></p>
        </div>
        <!-- Poll Creation -->
        <div class="container">          
            {% block body_block %}{% endblock %}
        </div>
        <br>
        <div class="bottombar">
                <p class="login"><a href="/polls/about/">about</a></p>
        </div>


        <!-- build:js scripts/vendor.js -->
        <!-- bower:js -->
        <script src="bower_components/jquery/jquery.js"></script>
        <!-- endbower -->
        <!-- endbuild -->

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>

    
        <!-- build:js scripts/plugins.js -->
    <!--    <script src="bower_components/sass-bootstrap/js/affix.js"></script>
        <script src="bower_components/sass-bootstrap/js/alert.js"></script>
        <script src="bower_components/sass-bootstrap/js/dropdown.js"></script>
        <script src="bower_components/sass-bootstrap/js/tooltip.js"></script>
        <script src="bower_components/sass-bootstrap/js/modal.js"></script>
        <script src="bower_components/sass-bootstrap/js/transition.js"></script>
        <script src="bower_components/sass-bootstrap/js/button.js"></script>
        <script src="bower_components/sass-bootstrap/js/popover.js"></script>
        <script src="bower_components/sass-bootstrap/js/carousel.js"></script>
        <script src="bower_components/sass-bootstrap/js/scrollspy.js"></script>
        <script src="bower_components/sass-bootstrap/js/collapse.js"></script>
        <script src="bower_components/sass-bootstrap/js/tab.js"></script>
     -->
     <!-- endbuild -->

        <!-- build:js({app,.tmp}) scripts/main.js
        <script src="scripts/main.js"></script>
        endbuild -->
</body>
</html>


        <!-- View Posted Polls 
        <div class="container">
            <div class="row">
                <div class="panel panel-default">
                  <div class="panel-heading">View your Polls</div>
                  <div class="panel-body">
                      <div class="row">
                        <div class="col-xs-6">
                            <ul>
                                {% for poll in user.polls %}
                                    <li>
                                        <a href="{% url 'polls:detail' poll.id %}">{{ poll.question}}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        
            
                      </div>
          
                  </div>
                </div>
            </div>
        </div>   --> 

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}


{% block body_block %}
    <h1>{{ poll.question }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' poll.id %}" method="post">
    {% csrf_token %}
    {% for choice in poll.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>

{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block body_block %}

    <div class="row">
        <div class="panel panel-default">
                <div class="panel-heading">Most Recent Polls</div>
                <div class="panel-body">
                    <div class="row">
                        <ul>
                            {% if latest_poll_list %}
                                <ul>
                            {% for poll in latest_poll_list %}
                                <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
                            {% endfor %}
                                </ul>
                            {% else %}
                            <p>No polls are available.</p>
                            {% endif %}
                        </ul>

                    </div>
                </div>
        </div>
    </div>
{% endblock %}

polls/templates/polls/login.html
{% extends 'polls/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block body_block %}
    <h1>Login</h1>

<!--
    <form id="login_form" method="post" action="/polls/login/" role="form">
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
            <input type="text" name="username" value="" size="50" />
        </div>
        Password: <input type="password" name="password" value="" size="50" />


        <input type="submit" value="submit" class="btn btn-primary" />
    </form>

-->
    <form id="login_form" method="post" action="/polls/login/" role="form">
    {% csrf_token %}
      <div class="form-group" id="login_form" method="post" action="/polls/login">
        <label for="exampleInputEmail1">Username</label>
        <input type="text" class="form-control" name="username" placeholder="Username">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" name="password" value="" size="50" placeholder="Password">
      </div>
      <div class="form-group">
        <p class="help-block">Or if you need an account, <a href="/polls/register">Register</a>.</p>
      </div>

      <button type="submit" class="btn btn-primary">Login</button>
    </form>

{% endblock %}

polls/templates/polls/makepoll.html
{% extends 'polls/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
        <div class="container">
            <div class="row">
                    {% crispy form %}
                <div id="choices_form">
                    {% crispy choiceform %}
                </div>
                <div id="add_field" class="btn btn-primary">+</div>
            </div>
        </div>

    <script src="http://code.jquery.com/jquery-2.1.0.min.js">
      </script>


    <script>
        $('#add_field').html('ADD FIERRRLD');
        //$('#add_field').click(function() {
        //  alert('clicked');
        //})

        // http://stackoverflow.com/questions/6099301/dynamically-adding-html-form-field-using-jquery
        $('#add_field').click(function() {
          alert('CLICKED!');
          $("<input type='text' value='ab' />")
           console.log('got here')
           .attr("id", "choices_form")
           .attr("name", "choices_form")
           .appendTo("id_form-0-choice_text");
          });
        </script>

{% endblock %}
    

polls/templates/polls/register.html
{% extends 'polls/base.html' %}
{% load crispy_forms_tags %}

{% block title %}RRRRegister{% endblock %}

{% block body_block %}
    <h1>Register</h1>

    {% if registered %}
    <strong>Thank you for registering!</strong>
    <a href="/polls/">Return to the homepage.</a><br />
    {% else %}
    <strong>Register here!</strong><br />
    <i>NOTE: Please don't use the same password for every site, any web developer could simply steal
    your passord and e-mail from a registration form and try it on all kinds of websites.</i>
    {% crispy user_form %}

<!--    <form id="user_form" method="post" action="/polls/register/"
            enctype="multipart/form-data">

        {% csrf_token %}

        <!-- Display each form. The as_p method wraps each element in a paragraph
             (<p>) element. This ensures each element appears on a new line,
             making everything look neater. -->
<!--        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <!-- Provide a button to click to submit the form. -->
<!--        <input type="submit" name="submit" value="Register" />
    </form>
        -->
    {% endif %}
{% endblock %}

polls/templates/polls/restricted.html
{% extends 'polls/base.html' %}
{% load static %}

{% block title %}Control Panel{% endblock %}

{% block body_block %}
    <h1>Restricted Page</h1>

    You can view this page because you are logged in!

{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block body_block %}

    <h1>{{ poll.question }}</h1>

    <ul>
    {% for choice in poll.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

{% endblock %}

polls/templates/polls/user.html
{% extends 'polls/base.html' %}

{% block body_block %}

    <div class="row">
        <div class="panel panel-default">
                <div class="panel-heading">Most Recent Polls by: {{ user }}</div>
                <div class="panel-body">
                    <div class="row">
                          {% if polls %}
                            {% for poll in polls %}
                              <ul>
                                <li><a href="{% url 'polls:detail' poll.id %}"> {{ poll.question }}</a></li>
                              </ul>
                            {% endfor %}

                            {% else %}
                              <p>No polls are available for this user.</p>
                          {% endif %}


                    </div>
                </div>
        </div>
    </div>
{% endblock %}